server:
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /api

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/travelling
    username: dba
    password: dba

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        "[format_sql]": false
    show-sql: false

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

debug: true